version: '2'
services:
  web:
    build: ./web
    ports: 
      - "3000:3000"
    environment:
      - NODE_MOD_DIR=/node_modules
      - STATIC_DIR=/client/dist
      - PORT=3000
    links:
      - api
  api:
    build: ./api
    links:
      - db
    environment:
      - PORT=80
    env_file:
      - .env
  db:
    image: postgres:9.4
    restart: always
    env_file:
      - .env
  migrations:
    build: ./migrations
    links:
      - db
    env_file:
      - .env
    # image: zokeber/postgresql:latest
    # # If the container is brought up more than once
    # # these variables need to be commented out.
    # # The startup routine breaks otherwise.
    # # ¯\_(ツ)_/¯
    # # env_file:
    # #   - .env
